openapi: 3.0.4
info:
  title: Contact Center log models
  description: Log models for logging services of contact center
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: {}

components:
  schemas:
    CommonLogModel:
      title: Общая модель лога
      description: Общая модель лога для всех микросервисов системы
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        tickets:
          $ref: '#/components/schemas/CCLogModel'
        #        comments:
        #          $ref: '#/components/schemas/CCLogModel'
        #        files:
        #          $ref: '#/components/schemas/CCLogModel'
        #        images:
        #          $ref: '#/components/schemas/CCLogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    CCLogModel:
      title: Модель лога для микросервиса Contact Center
      type: object
      properties:
        requestId:
          type: string
        operation:
          $ref: '#/components/schemas/CCLogOperation'
        requestTicket:
          $ref: '#/components/schemas/TicketLog'
        requestAssignment:
          $ref: '#/components/schemas/TicketAssignmentLog'
        responseTicket:
          $ref: '#/components/schemas/TicketLog'
        responseTickets:
          type: array
          items:
            $ref: '#/components/schemas/TicketLog'

    CCLogOperation:
      type: string
      enum:
        - create
        - update
        - get
        - list
        - assign
        - init
        - finish

    ErrorLogModel:
      title: Модель лога для ошибки
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string

    TicketLog:
      title: Модель лога для тикета
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        status:
          type: string
        priority:
          type: string
        clientId:
          type: string
        operatorId:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        permissions:
          type: array
          uniqueItems: true
          items:
            type: string

    TicketAssignmentLog:
      title: Модель лога назначения тикета
      properties:
        ticketId:
          type: string
        operatorId:
          type: string